language:
  python

python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

sudo:
  false

install:
  - pip install setuptools wheel

script:
  - python setup.py sdist bdist_wheel
  - pip install dist/*-any.whl -vvv
  - mkdir github
  - cp dist/*.gz github/
  - ls -lh github/

deploy:
  - provider: pypi
    username: "__token__"
    password:
      secure: "E1KEgBjLCyMRm5ORVE+/LR34bZO8Csk0PDKXMb4H+/AHJUea6D1TdO/wUD5h2hhwAtOqfSwlq5Y3PDfCVrS4iQAfj1OwP3hdUCVrdO6VfG0P9pTU0oYaDdtAKOKAObUzL6D8hK1BN8dHMfepIwJSoo37pSv6DoAnjm4UIsNa6rGvnBUAyYClgfUGqgtGRHZH4rB5yEd8n7BP8OC6EuAEmKtQ+/5Ba0wFSZnbhTLQFh+Qh/ckntX8J+GQWCxqcCX3EebpkvsskfOTKHxdGRcllw50ySNVt9VXwl1x7dFUz1r4ay9mxO7J3JKyqVrvHQfKDmyBmRut5r0TBked5DOnck4Xu/AL+2zUwLpA79cEWV0ND0pCEwymMvPinJcIBzrocVkpLUV5qelNJ7HubdYXFg2fqf0LN6YEJDZCInLtkh3B3XxThf4R9s+KfMIdr6fICcc/LxhnZk9twf1g1ZefDTFhd/NhThrkTOxn1xiD8MeqdMOO+YRgHz8bkwm1IdEBczZMq0gVbqZHn5TwY8IFOc4C4u5BtbYkhACs5TJ7LvYrGgh+FfIohkPG7Ufw/4xbxfhTtuAb2DJlFeB/cGpgUk4ZORV2gQKO+s0XuMLyQeidzrCsofIQIrZZw0oULM1BEOx7u+kViq44KDpv0bnxHMl8OMPLqAE9+8hbJ00uFGc="
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_existing: true
    on:
      condition: "$TRAVIS_PYTHON_VERSION == 3.6"
      tags: true
      branch: master

  - provider: releases
    token:
      secure: HnnLFAUcrPuiSlQO7Vi8EjQvInmONdkrmZINYH26+jy1l0Q0XVrwOG9NYqCmZQVRWS+PMKfMMLgQCsCoNEmUaQb7G/gStayy/01A7+DvnM/39fXZ0NgPd6OndERqamacr61A2N6pENAqNPCePm1tpljQ0utbmDVEascinR6/7gsk1+cjEs7pGy0Cn6yHjnT0HD6+oNhQ5PxeyTjHl6bRajiWhinWWVr65ldbu2q+e1yVJ6x3aHR83KCd65I33Cz19SFD4LN6XuTQtEJL2z3AOs6s8n3p0VNXRn+VwQQyXMseM4cnH43os35xyyGxzrBIIWU3E/yT8Jk72RIapVsSoJXxSmgXVffViVZkr9JnSP1ZaR8szjFy64UXxOIHqscxp5N54zROyIqTjj1yFYVDZqt6XrhGBs4S9c7A5dwhdTgKBMzj8wgzLfCbjygY05NjuTrPjqjwllGwyrSaxST/3Z+4MZC6jlRpPYhgag+lL75Cq/uwV8FHM1xtu2RvGPtaIHQBE6xn+tM8QkPSlMNCoSIGdUq1nBgbBh8L+2Z8SY0u2b3zMzMqyL2JX57hR5l/FEAS5R+bBohFp0VheASUSu0gEHNCZx6Gwm/8Dhgo1U4K5Bkt54PEKJUhlmGjd0S7p3lS9okhlX48WE7rol8YEDM2KYbzbtDXnIl/kA38AXU=
    file_glob: true
    file: github/*
    skip_cleanup: true
    on:
      condition: "$TRAVIS_PYTHON_VERSION == 3.6"
      tags: true
      branch: master
