version: 1.0.0 ({build})

environment:
  matrix:
    - PYTHON: C:\Python35
    - PYTHON: C:\Python36-x64

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - python -m pip install --upgrade pip setuptools wheel

build: off

test_script:
  - python setup.py sdist
  - python setup.py bdist_wheel
  - python setup.py bdist_wininst
