# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.6
          - python-version: 3.8
            DEPLOY_NAME: dist
          - python-version: 3.9
          - python-version: 3.8
            DEPLOY_NAME: all-voices
            ALL_VOICES: --all-voices

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        python -m pip install -U pip
        pip install -U setuptools wheel
    - name: Build Package
      run: python setup.py sdist bdist_wheel ${{ matrix.ALL_VOICES }}
    - name: Install dependencies for Test
      run: |
        pip install dist/*.whl
        wget -q https://raw.githubusercontent.com/Aculeasis/ff/main/rhv_bin.py -O rhv_bin.py
        pip install $(python3 rhv_bin.py linux amd64)
    - name: Test with unittest
      run: |
        git clone --depth=1 https://github.com/Aculeasis/rhvoice-proxy
        cd rhvoice-proxy
        python -m unittest discover -v -s rhvoice_wrapper/tests/

    - name: Upload Linux artifacts
      if: ${{ matrix.python-version == '3.8' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.DEPLOY_NAME }}
        path: dist/
        retention-days: 2

  deploy:
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/download-artifact@v4.1.7
      with:
        name: dist
        path: dist/
    - uses: actions/download-artifact@v4.1.7
      with:
        name: all-voices
        path: all-voices/

    - name: Deploy to GH Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.gz
          all-voices/*.whl
    - name: Deploy to PYPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
